 
	<!-- Revolution Slider -->
	<script type="text/javascript" src="js/rs-plugin/jquery.themepunch.plugins.min.js"></script>
    <script type="text/javascript" src="js/rs-plugin/jquery.themepunch.revolution.min.js"></script>
    
    <link rel="stylesheet" type="text/css" href="css/fullwidth.css" media="screen" />
	<link rel="stylesheet" type="text/css" href="css/revolution-settings.css" media="screen" />
    
    <script type="text/javascript">

				var tpj=jQuery;
				tpj.noConflict();

				tpj(document).ready(function() {

				if (tpj.fn.cssOriginal!=undefined)
					tpj.fn.css = tpj.fn.cssOriginal;

					tpj('.fullwidthbanner').revolution(
						{
							delay:9000,
							startwidth:890,
							startheight:450,

							onHoverStop:"on",						// Stop Banner Timet at Hover on Slide on/off

							thumbWidth:100,							// Thumb With and Height and Amount (only if navigation Tyope set to thumb !)
							thumbHeight:50,
							thumbAmount:3,

							hideThumbs:200,
							navigationType:"bullet",					//bullet, thumb, none, both	 (No Shadow in Fullwidth Version !)
							navigationArrows:"verticalcentered",		//nexttobullets, verticalcentered, none
							navigationStyle:"round",				//round,square,navbar

							touchenabled:"on",						// Enable Swipe Function : on/off

							navOffsetHorizontal:0,
							navOffsetVertical:20,

							stopAtSlide:-1,							// Stop Timer if Slide "x" has been Reached. If stopAfterLoops set to 0, then it stops already in the first Loop at slide X which defined. -1 means do not stop at any slide. stopAfterLoops has no sinn in this case.
							stopAfterLoops:-1,						// Stop Timer if All slides has been played "x" times. IT will stop at THe slide which is defined via stopAtSlide:x, if set to -1 slide never stop automatic



							fullWidth:"on",

							shadow:0								//0 = no Shadow, 1,2,3 = 3 Different Art of Shadows -  (No Shadow in Fullwidth Version !)

						});




			});
			</script>
    </div>
  
		<!--Revolution Slider -->
    	<div id="slider">
        
        
        <div class="fullwidthbanner-container">
					<div class="fullwidthbanner">
						<ul>


							<!-- FADE -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/thumbs/thumb1.jpg">

								<img src="images/slides/thumb1.jpg">

                                <div class="caption lft" data-x="0" data-y="10" data-speed="900" data-start="900" data-easing="easeOutExpo"><img src="images/slides/glare.png"></div>
                                <div class="caption lfl" data-x="-30" data-y="20" data-speed="900" data-start="1300" data-easing="easeOutBack"><img src="images/model1.png"></div>
								<div class="caption lft big_grey"  data-x="506" data-y="120" data-speed="400" data-start="1700" data-easing="easeOutExpo">Responsive Design</div>
								<div class="caption lft big_orange"  data-x="506" data-y="157" data-speed="400" data-start="1900" data-easing="easeOutExpo">Works well ondevices in portrait and landscape mode</div>
								<div class="caption lfr medium_grey"  data-x="510" data-y="220" data-speed="300" data-start="2500" data-easing="easeOutExpo">Revolution Slider included</div>
                                <div class="caption lfr small_text"  data-x="510" data-y="250" data-speed="300" data-start="2600" data-easing="easeOutExpo">Turn simple HTML markup into a responsive(mobile friendly) or fullwidth slider <br>with must-see-effects and meanwhile keep or build your SEO optimization <br>all content always readable for search engines. See the heaps of custom <br>transitions/animations for each object on the page! Customize this slider with just <br>a little HTML and CSS to your very needs.</div>                                
                                <div class="caption sfb" data-x="510" data-y="360" data-speed="1000" data-start="1800" data-easing="easeOutBack"><a target="_blank" href="http://themeforest.net/item/creative-responsive-html-template/3279410" class="btn-image">Purchase this theme</a></div>
							</li>
                            
                            
                            
                            
                            <!-- SLIDEUP -->
							<li data-transition="slideup" data-slotamount="7" data-thumb="images/thumbs/thumb2.png">

								<img src="images/slides/thumb2.jpg">

                                <div class="caption sfb" data-x="0" data-y="10" data-speed="900" data-start="900" data-easing="easeOutSine"><img src="images/slides/glare2.png"></div>
                                <div class="caption lft" data-x="140" data-y="50" data-speed="900" data-start="1700" data-easing="easeOutBack"><img src="images/model3.png"></div>
                                <div class="caption lfb big_grey"  data-x="20" data-y="350" data-speed="600" data-start="1800" data-easing="easeOutExpo">You can create spectacular backgrounds for your slides</div>
							</li>
                            
                            
                            
                            
                            <!-- FADE -->
							<li data-transition="fade" data-slotamount="10" data-thumb="images/thumbs/thumb1.jpg">

								<img src="images/slides/thumb1.jpg">

                                <div class="caption lft" data-x="0" data-y="10" data-speed="900" data-start="900" data-easing="easeOutExpo"><img src="images/slides/glare.png"></div>
                                <div class="caption lfl" data-x="-30" data-y="20" data-speed="900" data-start="1300" data-easing="easeOutBack"><img src="images/model2.png"></div>
								<div class="caption sfb big_grey"  data-x="506" data-y="120" data-speed="400" data-start="1700" data-easing="easeOutExpo">Tested on iPad with Chrome</div>
								<div class="caption lft big_orange"  data-x="506" data-y="157" data-speed="400" data-start="1900" data-easing="easeOutExpo">It's a responsive world now, sites must adapting</div>
								<div class="caption lfr medium_grey"  data-x="510" data-y="230" data-speed="300" data-start="2500" data-easing="easeOutExpo">Specification</div>
                                <div class="caption lfr small_text"  data-x="510" data-y="260" data-speed="300" data-start="2600" data-easing="easeOutExpo">Contrary to popular belief Lorem Ipsum is not simply random text. It has roots<br> in a piece of classical Latin literature from 45 BC making it over 2000 years old.<br> Richard McClintock a latin professor at Hampden-Sydney College in Virginia <br>looked up one of the more obscure words.</div>                                
                                <div class="caption sfb" data-x="510" data-y="360" data-speed="1000" data-start="1800" data-easing="easeOutBack"><a href="#" class="btn-image">Read more</a></div>
							</li>

							




						</ul>
						<div class="tp-bannertimer"></div>
					</div>
				</div>                
        	
        
        </div>
        <!-- /Revolution Slider -->




        
        
        <!-- Main Container -->
<div id="body-wrapper">
    
    
    <!-- Content -->
    <div id="content" class="container clearfix">

        <hr class="50">

        
        <!-- Features -->
        
        <div id="features">
        
            <div class="feature one-fourth">
                <div class="feature-icon"><img src="images/services_icon_01.png" alt="" /></div>
                <div class="feature-description">
                    <h4>Responsive Layout</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et ipsum tellus, vitae sagittis enim. Morbi ultricies ultrices elit vitae</p>                
                </div>
            </div>
            
            <div class="feature one-fourth second">
                <div class="feature-icon"><img src="images/services_icon_02.png" alt="" /></div>
                <div class="feature-description">
                    <h4>HTML5 / CSS3</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et ipsum tellus, vitae sagittis enim. Morbi ultricies ultrices elit vitae</p>                
                </div>
            </div>
            
            <div class="feature one-fourth">
                <div class="feature-icon"><img src="images/services_icon_03.png" alt="" /></div>
                <div class="feature-description">
                    <h4>Modern & Clean</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et ipsum tellus, vitae sagittis enim. Morbi ultricies ultrices elit vitae</p>                
                </div>
            </div>
            
            <div class="feature one-fourth last">
                <div class="feature-icon"><img src="images/services_icon_04.png" alt="" /></div>
                <div class="feature-description">
                    <h4>Easily Customisable</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et ipsum tellus, vitae sagittis enim. Morbi ultricies ultrices elit vitae</p>                
                </div>
            </div>
        
        </div>
        <!-- /Features -->
        
        
        
        
        
        
        
       
        
        
        
        
        
        
        
        
        
    
    </div>
    <!-- /Content -->

		
        

    
        
        
</div>
<!-- /Main Container -->       
