<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Archon Admin Template</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Loading Bootstrap -->
	<link href="/admin_template/bootstrap/css/bootstrap.css" rel="stylesheet">

	<!-- Loading Stylesheets -->    
	<link href="/admin_template/css/archon.css" rel="stylesheet">
	<link href="/admin_template/css/responsive.css" rel="stylesheet">
	<link href="/admin_template/css/login.css" rel="stylesheet">
	<!-- Loading Custom Stylesheets -->    
	<link href="/admin_template/css/custom.css" rel="stylesheet">

	<!-- Loading Custom Stylesheets -->    
	<link href="/admin_template/css/custom.css" rel="stylesheet">

	<link rel="shortcut icon" href="/admin_template/images/favicon.ico">

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<![endif]-->
</head>
<body>
	<div class="box-holder row">
		<!-- Title -->
		<h1>Login</h1><hr>
	
                <?php
                    print $this->form;
                ?>
                
		<hr>

	</div>

</body>
</html>
