       <!-- Accordion -->
   <script type="text/javascript" src="/js/accordion.js"> </script>
   <!-- /Accordion -->
   

    <!-- Content -->
    <div id="content" class="container clearfix">

    
        
        <!-- Page title -->
        <nav id="page-title" >
        
        	<h1><?= $this->blog_post['naziv_posta']; ?></h1>
        
        </nav>
        <!-- /Page title -->
        
        
        
        <!-- Main Content -->
        <div id="main">
        
        	<!-- News Post -->
            <div class="post">
                
                <ul class="post-details">
                    <li class="author"><a href="#">Admin</a></li>
                    <li class="date"><?= date('F j,Y',$this->blog_post['vreme_unosa']) ?></li>
                    <li class="tag"><a href="#"><?= $this->blog_post['naziv_kategorije'] ?></a></li>
                </ul>
                <div class="post-content">
                    <?php
                    if(!empty($this->blog_post['slika_posta'])){
                    ?>
                    <img src="/images/blog_post_image/<?= $this->blog_post['slika_posta'] ?>" alt="" class="image" />
                    <?php
                    }
                    ?>
                    <p>
                        <?= $this->blog_post['opis_posta'] ?>
                    </p>
                    
                </div>
            </div>
            <!-- /News Post -->

        <!-- Main Content -->
        </div>
      <!-- Sidebar -->
        <div id="sidebar">
        
			
             <!-- Search -->
            <h4>Search</h4>
            <form action="/pretraga/pretrazi" id="searchform" method="get">
                <input type="text" name="pretraga" onfocus="if(this.value == 'Search in blog') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Search in blog'; }" value="Search in blog" class="search" id="search">
            </form>
            <!-- /Search -->


            <!-- Blog Categories -->
            <div class="widget">
                <h4>Blog Categories</h4>
                <ul class="categories">
                    <?php
                        foreach($this->blog_kat as $kat){
                            echo '<li><a href="/category/'.$kat['id_blog_kat'].'">'.$kat['naziv_kategorije'].'</a></li>';
                        }
                        ?>
                </ul>
            </div>
            <!-- /Blog Categories -->
            
            
            

            <!-- Text Widget -->
            <div class="widget">
                <h4>Text Widget</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dui orci, dapibus non luctus, ultrices vel nunc. Donec lacinia mattis erat amet.</p>
            </div>
            <!-- /Text Widget -->
            
            

            

            <!-- Accordion -->
            <div class="widget clearfix">
                <h4>Accordion widget</h4>
                
                <div class="accordionButton first">About Us</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">How we work</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">References</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">Contact us</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                
            </div>
            <!-- Accordion -->

        </div>
        <!-- /Sidebar -->

    
    </div>
    <!-- /Content -->

		