<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Admin panel</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<!-- Loading Bootstrap -->
	<link href="/admin_template/bootstrap/css/bootstrap.css" rel="stylesheet">

	<!-- Loading Stylesheets -->    
	<link href="/admin_template/css/archon.css" rel="stylesheet">
	<link href="/admin_template/css/responsive.css" rel="stylesheet">
	<link href="/admin_template/css/prettify.css" rel="stylesheet">

	<!-- Loading Custom Stylesheets -->    
	<link href="/admin_template/css/custom.css" rel="stylesheet">

	<!-- Loading Custom Stylesheets -->    
	<link href="/admin_template/css/custom.css" rel="stylesheet">

	<link rel="shortcut icon" href="/admin_template/images/favicon.ico">

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
	<!--[if lt IE 9]>
	<script src="js/html5shiv.js"></script>
	<![endif]-->
</head>
<body>
	<div class="frame">
		<div class="sidebar">
			<div class="wrapper">

				<!-- Replace the src of the image with your logo -->
				<a href="/" class="logo"><img src="/admin_template/images/logo.png" alt="Archon Admin" /></a>
				<ul class="nav  nav-list">

					<!-- sidebar input search box -->
					<li class="nav-search">
						<div class="form-group">
							<input type="text" class="form-control nav-search" placeholder="Search through site" />
							<span class="input-icon fui-search"></span>
						</div>
					</li>

					<!-- Sidebar header @add class nav-header for sidebar header -->
					<li class="nav-header">Overview</li>
					<li  class="active"><a href="/admin"><i class="icon-dashboard"></i>Dashboard </a></li>
					
					<!-- Sidebar header @add class nav-header for sidebar header -->
					<li class="nav-header">Projekti</li>
                                        <li><a href="/admin/unoskategorija"><i class="icon-list-alt"></i>Unos Kategorija za projekte</a></li>
                                        <li><a href="/admin/unosprojekata"><i class="icon-list-alt"></i>Unos Projekata</a></li>
                                        <li class="nav-header">Blog</li>
					<li><a href="/admin/unosblogkategorije"><i class="icon-archive"></i>Unos blog kategorija</a></li>
					<li><a href="/admin/unosblogposta"><i class="icon-picture"></i>Unos novog posta</a></li>
					<li><a href="login.html"><i class="icon-signin"></i>Login</a></li>
					<li> <!-- Example for second level menu -->
						<a class="dropdown" href="#"><i class="icon-user"></i> Profile <span class="label">2</span></a>
						<ul>
							<li><a href="profile.html"><i class="icon-usre"></i> Model One</a></li>
							<li><a href="profileTwo.html"><i class="icon-usre"></i> Model Two</a></li>
						</ul>	
					</li>
					<li> <!-- Example for second level menu -->
						<a class="dropdown" href="#"><i class="icon-folder-close-alt"></i> Dropdown menu <span class="label">3</span></a>
						<ul>
							<li><a href="#"><i class="icon-hdd"></i> Submenu item</a></li>
							<li><a href="#"><i class="icon-coffee"></i>Submenu item</a></li>
							<li><a href="#"><i class="icon-crop"></i> Submenu item</a></li>
						</ul>	
					</li>

					<!-- Sidebar header @add class nav-header for sidebar header -->
					<li class="nav-header">Components</li>
					<li><a href="tables.html"><i class="icon-table"></i>Tables</a></li>
					<li> <!-- Example for second level menu -->
						<a class="dropdown" href="#"><i class="icon-folder-close-alt"></i> Charts <span class="label">3</span></a>
						<ul>
							<li><a href="nvd.html"><i class="icon-hdd"></i> NVD</a></li>
							<li><a href="flot.html"><i class="icon-coffee"></i>Flot</a></li>
							<li><a href="knobs.html"><i class="icon-coffee"></i>Knobs</a></li>
						</ul>	
					</li>
					<li><a href="typography.html"><i class="icon-text-width"></i>Typography</a></li>
					<li>
						<a class="dropdown" href="forms.html"><i class="icon-list-alt"></i>Forms  <span class="label">4</span></a>
						<ul>
							<li><a href="form-elements.html"><i class="icon-indent-right"></i> Form Elements</a></li>
							<li><a href="forms.html"><i class="icon-indent-left"></i>Forms</a></li>
							<li><a href="form-wizard.html"><i class="icon-coffee"></i>Form wizard</a></li>
							<li><a href="file-uploads.html"><i class="icon-indent-right"></i> File Upload</a></li>
						</ul>	
					</li>
					<li><a href="icons.html"><i class="icon-truck"></i>Icons</a></li>
				</ul>

			</div><!-- /Wrapper -->
		</div><!-- /Sidebar -->

		<!-- Main content starts here-->
		<div class="content">
			<div class="navbar">
				<a href="#" onclick="return false;" class="btn pull-left toggle-sidebar"><i class="icon-list"></i></a>
				<a class="navbar-brand" href="index.html">Archon</a>

				<!-- Top right user menu -->
				<ul class="nav navbar-nav user-menu pull-right">
					<!-- First nav user item -->
					<li class="dropdown hidden-xs">
						<a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-envelope-alt"></i></a>
						<ul class="dropdown-menu right inbox">
							<li class="dropdown-menu-title">
								INBOX <span>(25)</span>
							</li>
							<li>
								<img src="/admin_template/images/theme/avatarTwo.png" alt="" class="avatar">
								<div class="message">
									<span class="username">Anusha</span> 
									<span class="mini-details">(6) <i class="icon-paper-clip"></i></span>
									<span class="time pull-right"> 06:58 PM</span>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ... </p>
								</div>
							</li>
							<li>
								<img src="/admin_template/images/theme/avatarFive.png" alt="" class="avatar">
								<div class="message">
									<span class="username">Veeru</span> 
									<span class="mini-details">(2) <i class="icon-paper-clip"></i></span>
									<span class="time pull-right"> 09:58 AM</span>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ... </p>
								</div>
							</li>
							<li>
								<img src="/admin_template/images/theme/avatarSix.png" alt="" class="avatar">
								<div class="message">
									<span class="username">Nag</span> 
									<span class="mini-details">(6) <i class="icon-paper-clip"></i></span>
									<span class="time pull-right">Yesterday</span>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ... </p>
								</div>
							</li>
							<li>
								<img src="/admin_template/images/theme/avatarSeven.png" alt="" class="avatar">
								<div class="message">
									<span class="username">Harish</span> 
									<span class="mini-details"> <i class="icon-picture"></i></span>
									<span class="time pull-right">14/12/2013</span>
									<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's ... </p>
								</div>
							</li>
							<li class="dropdown-menu-footer">
								<a href="#">View All Messages</a>
							</li>
						</ul>
					</li><!-- /dropdown -->

					<!-- Second nav user item -->
					<li class="dropdown hidden-xs">
						<a class="dropdown-toggle" data-toggle="dropdown"><i class="icon-bell"></i></a>
						<ul class="dropdown-menu right notifications">
							<li class="dropdown-menu-title">
								Notifications
							</li>
							<li>
								<i class="icon-cog avatar text-success"></i>
								<div class="message">
									<span class="username text-success">New settings activated</span> 
									<span class="time pull-right"> 06:58 PM</span>
								</div>
							</li>
							<li>
								<i class="icon-shopping-cart avatar text-danger"></i>
								<div class="message">
									<span class="username text-danger">You have 2 returns</span> 
									<span class="time pull-right"> 04:29 PM</span>
								</div>
							</li>
							<li>
								<i class="icon-user avatar text-success"></i>
								<div class="message">
									<span class="username text-success">New User registered</span> 
									<span class="time pull-right"> Yesterday</span>
								</div>
							</li>
							<li>
								<i class="icon-comment avatar text-info"></i>
								<div class="message">
									<span class="username text-info">New Comment received</span> 
									<span class="time pull-right"> Yesterday</span>
								</div>
							</li>
							<li>
								<i class="icon-cog avatar text-warning"></i>
								<div class="message">
									<span class="username text-warning">User deleted</span> 
									<span class="time pull-right"> 2 days ago</span>
								</div>
							</li>
							<li>
								<i class="icon-dollar avatar"></i>
								<div class="message">
									<span class="username">Earned 200 points</span> 
									<span class="time pull-right">3 days ago</span>
								</div>
							</li>
							<li>
								<i class="icon-hdd avatar text-danger"></i>
								<div class="message">
									<span class="username text-danger">Memory size exceeded </span> 
									<span class="time pull-right"> 1 week ago</span>
								</div>
							</li>

							<li class="dropdown-menu-footer">
								<a href="#">View All Notifications</a>
							</li>
						</ul>
					</li><!-- / dropdown -->

					<li class="dropdown user-name">
                                            
                                             <?php 
                                                $logovan=Zend_Auth::getInstance(); 
                                                $korisnik=$logovan->getIdentity();
                                            ?>
						<a class="dropdown-toggle" data-toggle="dropdown"><img src="/admin_template/images/theme/avatarSeven.png" class="user-avatar" alt="" /><?php print $korisnik->korisnicko_ime; ?></a>
                                                    <ul class="dropdown-menu right inbox user">
                                                        <li class="user-avatar">
                                                                <img src="/admin_template/images/theme/avatarSeven.png" class="user-avatar" alt="" />
                                                                <?= $korisnik->korisnicko_ime; ?>
                                                        </li>
							<li>
								<i class="icon-user avatar"></i>
								<div class="message">
									<span class="username">Profile</span> 
								</div>
							</li>
							<li>
								<i class="icon-cogs avatar"></i>
								<div class="message">
									<span class="username">Settings </span> 
								</div>
							</li>
							<li>
								<i class="icon-book avatar"></i>
								<div class="message">
									<span class="username">Help </span> 
								</div>
							</li>
							<li><a href="/logout">Logout</a></li>
						</ul>
					</li><!-- / dropdown -->				
				</ul><!-- / Top right user menu -->

			</div><!-- / Navbar-->

<?php echo $this->layout()->content; ?>

		</div><!-- / Content @5 -->

		<div class="row footer">
			<div class="col-md-12 text-center">
				© 2013 <a href="http://bootstrapguru.com/">Bootstrap Guru</a>
			</div>
		</div>
	</div> <!-- Frame -->


	<!-- Load JS here for greater good =============================-->
	<script src="/admin_template/js/jquery-1.8.3.min.js"></script>
	<script src="/admin_template/js/jquery-ui-1.10.3.custom.min.js"></script>
	<script src="/admin_template/js/jquery.ui.touch-punch.min.js"></script>
	<script src="/admin_template/js/bootstrap.min.js"></script>
	<script src="/admin_template/js/bootstrap-select.js"></script>
	<script src="/admin_template/js/bootstrap-switch.js"></script>
	<script src="/admin_template/js/jquery.tagsinput.js"></script>
	<script src="/admin_template/js/jquery.placeholder.js"></script>
	<script src="/admin_template/js/bootstrap-typeahead.js"></script>
	<script src="/admin_template/js/application.js"></script>
	<script src="/admin_template/js/moment.min.js"></script>
	<script src="/admin_template/js/jquery.dataTables.min.js"></script>
	<script src="/admin_template/js/jquery.sortable.js"></script>
	<script type="text/javascript" src="/admin_template/js/jquery.gritter.js"></script>

	<!-- Charts  =============================-->
	<script src="/admin_template/js/charts/jquery.flot.js"></script>
	<script src="/admin_template/js/charts/jquery.flot.resize.js"></script>
	<script src="/admin_template/js/charts/jquery.flot.stack.js"></script>
	<script src="/admin_template/js/charts/jquery.flot.pie.min.js"></script>	
	<script src="/admin_template/js/charts/jquery.sparkline.min.js"></script>	
	<script src="/admin_template/js/jquery.knob.js"></script>


	<!-- NVD3 graphs  =============================-->
	<script src="/admin_template/js/nvd3/lib/d3.v3.js"></script>
	<script src="/admin_template/js/nvd3/nv.d3.js"></script>
	<script src="/admin_template/js/nvd3/src/models/legend.js"></script>
	<script src="/admin_template/js/nvd3/src/models/pie.js"></script>
	<script src="/admin_template/js/nvd3/src/models/pieChart.js"></script>
	<script src="/admin_template/js/nvd3/src/utils.js"></script>
	<!--<script src="/admin_template/js/nvd3/sample.nvd3.js"></script>-->

	<!-- Map and icons on map-->
	<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
	<script src="/admin_template/js/map-icons.js"></script>

	<script src="/admin_template/js/archon.js"></script>
	<script src="/admin_template/js/knobs-custom.js"></script>
	<script src="/admin_template/js/sparkline-custom.js"></script>
	<!--<script src="/admin_template/js/dashboard-custom.js"></script>-->
</body>
</html>
