<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <title>Creative - Responsive HTML Template - ClaPat Studio</title>
    
    <meta name="description" content="">
    <meta name="author" content="">
    

    <link rel="stylesheet" type="text/css" href="/css/style.css" />
    <link rel="alternate stylesheet" type="text/css" media="screen" title="green-theme" href="/css/style-green.css" />
    <link rel="alternate stylesheet" type="text/css" media="screen" title="orange-theme" href="/css/style-orange.css" />
    <link rel="stylesheet" type="text/css" href="/css/prettyPhoto.css"/>
    
    
    
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
    
    
   <!-- Css Switcher --> 
   <script src="/js/styleswitch.js" type="text/javascript"></script>
 
    <!-- Responsive Navigation -->
    <script src="/js/selectnav.min.js"></script>
    <!-- /Responsive Navigation -->
    
   
	

    
</head>
<?php
                
    $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
    $action = Zend_Controller_Front::getInstance()->getRequest()->getActionName();   


?>
<?php
    if($controller=='contact' && $action=='index'){
    ?>
<body onload="initialize()">
<!-- / Header Background -->	 
<?php
    }else{
        echo'<body>';
    }
?>




<!-- Header Background -->
<div id="header-bg"></div>
<!-- / Header Background -->


<?php
    if( ($controller=='contact' && $action=='index') || ($controller=='about' && $action=='index') || ($controller=='blog' && $action=='index') || ($controller=='BlogPost' && $action=='index') ){
    ?>
<div id="sub-header-bg"></div>
<!-- / Header Background -->	 
<?php
    }
?>


<!-- Main Container -->
<div id="body-wrapper">


	<!-- Header -->
    <div id="header" >

        <a href="/" id="logo"></a>
        
        
        <!-- Navigation -->
        <ul id="navigation">
            
            <li class="<?=($controller=='index' && $action=='index') ? 'current' : ''?>">
                <a href="/">Home</a>
              
            </li>

            
            <li class="<?=($controller=='portfolio' && $action=='index') ? 'current' : ''?>">
                <a href="/portfolio">Portfolio</a>
<!--                <ul>
                	<li><a href="portfolio_4_col.html">4 Columns</a></li>
                    <li><a href="portfolio_3_col.html">3 Columns</a></li>
					<li><a href="portfolio_2_col.html">2 Columns</a></li>
                    <li><a href="portfolio_details.html">Single Project</a></li>
                    
                </ul>-->
            </li>
            
            <li class="<?=($controller=='blog' && $action=='index') ? 'current' : ''?>">
                <a href="/blog">Blog</a>
            </li>
            
            <li class="<?=($controller=='about' && $action=='index') ? 'current' : ''?>">
                <a href="/about">About Us</a>
            </li>
            
            <li class="<?=($controller=='contact' && $action=='index') ? 'current' : ''?>">
                <a href="/contact">Contact</a>
            </li>
            
                
            
            
        </ul>
        <!-- /Navigation -->   
        
    
    </div>
    <!-- /Header -->
    

    


<?php echo $this->layout()->content; ?>


</div>
<!-- /Main Container -->    
<!-- Footer -->
        <div id="footer">
        
        	<div id="footer-center" class="container">
            
            	<div class="footer-left">
                	
                    <ul class="footer-menu">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Features</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">News</a></li>
                        <li class="footer-last"><a href="#">Contact</a></li>
                    </ul>
                    
                   
                    
                    <ul class="footer-address">
                    	<li><img src="/images/home-icon.png"/>314 Columbus Ave. , San Francisco , CA 94133 </li>
                        <li><img src="/images/phone-icon.png"/>(123) 456-78910</li>
                        <li><img src="/images/email-icon.png"/>office@creative.com</li>
               		</ul>
                
                </div>	
                
                
                <div class="footer-right" id="footer-newsletter">
                
                	
                    <p>Newsletter</p>
                    <form id="newsletter"  method="post">
                        <input type="text" onfocus="if(this.value == 'E-mail here') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'E-mail here'; }" value="E-mail here" class="newsletter">
                        <button type="submit">Submit</button>
                    </form>
                
                </div>
                
                
            
            </div>
            
            
            
            
            <div id="footer-bottom">
            
            	<div id="footer-center-bottom" class="container">
            
            	<!-- Copyright -->
                <ul class="copyright">
                    <li>2012 © Creative Media. All rights reserved</li>
                </ul>
                <!-- /Copyright -->
    
                <!-- Social Links -->
                <ul class="social-links">                   
                    <li class="facebook"><a href="#">Facebook</a></li>
                    <li class="twitter"><a href="#">Twitter</a></li>
                    <li class="vimeo"><a href="#">Vimeo</a></li>
                    <li class="linkedin"><a href="#">LinkedIn</a></li>
                    <li class="dribble"><a href="#">Dribbleo</a></li>
                    <li class="google"><a href="#">Google</a></li>
                </ul>
                <!-- /Social Links -->
                
                </div>
            
            </div>
            
            
            
            
        
        </div>
        <!-- /Footer -->


		<!-- CSS Switcher - Remove this -->
<!--        <div id="settings">
        <a class="colorbox colorblue" href="javascript:chooseStyle('none', 60)" checked="checked"></a>
                <a class="colorbox colorgreen" href="javascript:chooseStyle('green-theme', 60)"></a>
                <a class="colorbox colororange" href="javascript:chooseStyle('orange-theme', 60)"></a>   
        </div>-->
        <!--/CSS Switcher - Remove this -->
        
        

		
</body>

 
</html>
