
    <link rel="stylesheet" href="/css/flexslider.css" type="text/css">
   <!-- Accordion -->
    <script type="text/javascript" src="/js/accordion.js"> </script>

<script>
    $(document).ready(function(){
    
        // hide #back-top first
        $("#back-top").hide();
        
        // fade in #back-top
        $(function () {
            $(window).scroll(function () {
                if ($(this).scrollTop() > 100) {
                    $('#back-top').fadeIn();
                } else {
                    $('#back-top').fadeOut();
                }
            });
    
            // scroll body to 0px on click
            $('#back-top a').click(function () {
                $('body,html').animate({
                    scrollTop: 0
                }, 800);
                return false;
            });
        });
    
    });
    </script>    

<!-- FlexSlider -->    
    <script src="js/jquery.flexslider.js"></script>

	<script type="text/javascript">
            $(function(){
              SyntaxHighlighter.all();
            });
            $(window).load(function(){
              $('.flexslider').flexslider({
                animation: "fade",
                start: function(slider){
                  $('body').removeClass('loading');
                }
              });
            });
	</script>
    <!-- /FlexSlider -->    


    <!-- Content -->
    <div id="content" class="container clearfix">
    
    
    
    
    
            <!-- Back to top -->
            <p id="back-top" style="display: block;">
                <a href="#top"><span></span></a>
            </p>
            <!-- /Back to top -->
            
            
            
            
    
    
        
        <!-- Page title -->
        <nav id="page-title" >
        
        	<h1>Our blog page</h1>
        
        </nav>
        <!-- /Page title -->
        
        
        
        <!-- Main Content -->
        <div id="main">
        
        
            
            <!-- News Post -->
            <div class="post">
            <?php
                foreach($this->get_post as $post){
                    echo '<div class="title">';
                    echo '<a href="/post/'.$post['id_posta'].'"><h2>'.$post['naziv_posta'].'</h2></a>';
                    echo '</div>';
                    echo '<ul class="post-details">';
                    echo '<li class="author"><a href="#">Admin</a></li>';
                    echo '<li class="date">'.date('F j,Y',$post['vreme_unosa']).'</li>';
                    echo '<li class="tag"><a href="#">Web</a></li>';
                    echo '</ul>';
                    echo '<div class="post-content">';
                    echo '<a href="#" title=""><img src="/images/flexslide3.jpg" alt="" class="image" /></a>';
                    echo '<p>';
                    echo substr($post['opis_posta'],0,500). '...';
                    echo '</p>';
                    echo '<a href="/post/'.$post['id_posta'].'">Read more</a>';
                    echo '</div>';
                }
            ?>
            </div>  
            <!-- /News Post -->

            <!-- Pagination -->
            <ul class="pagination">
                <li class="prev"><a href="#">Prev</a></li>
                <li><a href="#">1</a></li>
                <li class="current">2</li>
                <li><a href="#">3</a></li>                
                <li><a href="#">4</a></li>                
                <li class="next"><a href="#">Next</a></li>
            </ul>
            <!-- /Pagination -->

        <!-- Main Content -->
        </div>
        

            
            <!-- Sidebar -->
        <div id="sidebar">
			
            
            <!-- Search -->
            <h4>Search</h4>
            <form action="/pretraga/pretrazi" id="searchform" method="get">
                <input type="text" name="pretraga" onfocus="if(this.value == 'Search in blog') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Search in blog'; }" value="Search in blog" class="search" id="search">
            </form>
            <!-- /Search -->
            
            
            <!-- Blog Categories -->
            <div class="widget">
                <h4>Blog Categories</h4>
                
                <ul class="categories">
                     <?php
                        foreach($this->blog_kat as $kat){
                            echo '<li><a href="/category/'.$kat['id_blog_kat'].'">'.$kat['naziv_kategorije'].'</a></li>';
                        }
                        ?>
                </ul>
            </div>
            <!-- /Blog Categories -->
            
            
            

            <!-- Text Widget -->
            <div class="widget">
                <h4>Text Widget</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras dui orci, dapibus non luctus, ultrices vel nunc. Donec lacinia mattis erat amet.</p>
            </div>
            <!-- /Text Widget -->
            
            

            

            <!-- Accordion -->
            <div class="widget clearfix">
                <h4>Accordion widget</h4>
                
                <div class="accordionButton first">About Us</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">How we work</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">References</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                <div class="accordionButton">Contact us</div>
                <div class="accordionContent">Lorem ipsum dolor sit amet, consectetur adipiscing elit ultrices vel.</div>
                
                
            </div>
            <!-- Accordion -->
            
            
            
            

            <!-- Twitter Feed -->
            <div class="widget">
                <h4>Latest Tweets</h4>
                <div class="twitter-post">
                
                    <p>Lorem ipsum dolor sit amet, consectetur vulputate ullamcorper tellus libero. <a href="#">http://creative.com/twitter</a></p>
                    
                    <p>Lorem ipsum dolor sit amet, consectetur vulputate ullamcorper tellus libero. <a href="#">http://creative.com/twitter</a></p>
                    
                    <p>Lorem ipsum dolor sit amet, consectetur vulputate ullamcorper tellus libero. <a href="#">http://creative.com/twitter</a></p>
                    
                </div>
            </div>
            <!-- /Twitter Feed -->

            

        </div>
        <!-- /Sidebar -->
            
            
            
        
        
        
        
        
        
        
        
        
        
        
        </div>    