
<!-- AJAX Contact Form -->
 <script type="text/javascript" src="http://code.jquery.com/jquery-latest.js"></script>
<script type="text/javascript" src="/js/jquery.jigowatt.js"></script><!-- AJAX Form Submit -->
 <!-- AJAX Contact Form -->


<!-- Google map -->
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript">
        function initialize() {
            var latlng = new google.maps.LatLng(44.8152453,20.4203223);
            var settings = {
                zoom: 13,
                center: latlng,
                mapTypeControl: false,
                mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
                navigationControl: false,
                navigationControlOptions: {style: google.maps.NavigationControlStyle.SMALL},
                mapTypeId: google.maps.MapTypeId.ROADMAP};
            var map = new google.maps.Map(document.getElementById("map_canvas"), settings);
            var contentString = '<div id="content">'+
                '<div id="siteNotice">'+
                '</div>'+
                '<h2 id="firstHeading" class="firstHeading">Creative Media</h2>'+
                '<div id="bodyContent">'+
                '<p>This is a pop up. You can put here your text.</p>'+
                '</div>'+
                '</div>';
            var infowindow = new google.maps.InfoWindow({
                content: contentString
            });
            
            var companyImage = new google.maps.MarkerImage('images/marker.png',
                new google.maps.Size(70,85),<!-- Width and height of the marker -->
                new google.maps.Point(0,0),
                new google.maps.Point(35,220)<!-- Position of the marker -->
            );
    
            var companyShadow = new google.maps.MarkerImage('images/marker-shadow.png',
                new google.maps.Size(108,56),<!-- Width and height of the shadow marker -->
                new google.maps.Point(0,0),
                new google.maps.Point(30,190));<!-- Position of the shadow marker -->
    
            var companyPos = new google.maps.LatLng(44.8152453,20.4203223);
    
            var companyMarker = new google.maps.Marker({
                position: companyPos,
                map: map,
                icon: companyImage,
                shadow: companyShadow,
                title:"Creative Media",
                zIndex: 3});
            
            
            
            google.maps.event.addListener(companyMarker, 'click', function() {
                infowindow.open(map,companyMarker);
            });
        }
    </script>
    <!--/Google map -->

<!-- Content -->
    <div id="content" class="container clearfix">
    

        <!-- Page title -->
        <nav id="page-title" >
        
        	<h1>Contact us</h1>
        
        </nav>
        <!-- /Page title -->
        
         
        
        
    
    </div>
    <!-- /Content -->        

    
        
</div>
<!-- /Main Container -->  




      
	<!-- Contact Container --> 
	<div id="contact-map">
    	
        <!-- Contact Info -->
    	<div id="contact-info">
        
        
        	<div class="one-fourth">
            
            	<div id="contact-details">
            	
                    <h4>Contact details</h4>
                    
                    <p> 
                        30 South Park Avenue<br>
                        San Francisco, CA 94108<br>
                        USA<br><br>
                        
                        Phone: (123) 456-7890<br>
                        Fax: +08 (123) 456-7890<br>
                        Email: contact@creative.com<br>
                        Web: creative.com
                    </p>
                
                </div>
            
            </div>
        
        	
            
            	<div class="three-fourth last">
                
                	<!-- Comments Form -->
            		<div id="contact-form">
            		
                    
                        <h4>Send us a message</h4>
        				
                        <div id="message"></div>
                        <form method="post" action="/contact/sendform" name="contactform" id="contactform">
                        	
                            <input name="name" type="text" id="name" size="30"  onfocus="if(this.value == 'Name') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Name'; }" value="Name" >
                            <input name="email" type="text" id="email" size="30" onfocus="if(this.value == 'E-mail') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'E-mail'; }" value="E-mail" >
                            <input name="phone" type="text" id="phone" size="30" onfocus="if(this.value == 'Phone') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Phone'; }" value="Phone" class="last" >
                            <textarea name="comments" cols="40" rows="3" id="comments" onfocus="if(this.value == 'Message') { this.value = ''; }" onblur="if(this.value == '') { this.value = 'Message'; }" value="Message">Message</textarea>
                            
                            <input type="submit" class="btn-image" id="submit" value="Submit" />
                            
                        </form>
                
                	</div>
                	 <!-- /Comments Form -->
            </div>
               
        
        </div>		
		<!-- /Contact Info -->
        
        
            <!-- Map-->
            <div id="map_canvas" style="width:100%; height:100%"></div>
            <!--End Map-->
        
        
        </div>
        <!-- /Contact Container -->
        
        