
<div class="row">
    <div class="col-md-12">
            <div class="panel panel-archon">
                    <div class="panel-heading">
                            <h3 class="panel-title">
                                    Unos Projekata
                                    <span class="pull-right">
                                            <a  href="#" class="panel-minimize"><i class="icon-chevron-up"></i></a>
                                    </span>
                            </h3>
                    </div>
                    <div class="panel-body">
<?php
        echo $this->form;
        
        if(isset($this->status)){
            
            if($this->status){
                ?>
                    <p class="bg-success">Projekat je uspešno unet.</p>
                <?php
            }else{
                ?>
                    <p class="bg-danger">Projekat nije unet.</p>
                <?php
            }
            
        }
      ?>
                    
<table class="table table-bordered table-hover table-striped tablesorter">
    <tr>
        <th>
            ID
        </th>
        <th>
            Naziv
        </th>
        <th>
            Opis
        </th>
        <th>
            Link
        </th>
        <th>
            Vreme unosa
        </th>
        <th  colspan="2">                    
        </th>
    </tr>
    <?php
          foreach ($this->get_projekti as $pro) {
    
            echo '<tr>';                        
                echo '<td>';
                    echo $pro['id_projekta'];
                echo '</td>';
                echo '<td class="naziv_projekta">';
                    echo $pro['naziv_projekta'];
                echo '</td>';
                echo '<td class="opis_projekta">';
                    echo $pro['opis_projekta'];
                echo '</td>';
                echo '<td class="link_projekta">';
                    echo $pro['link_projekta'];
                echo '</td>';
                echo '<td>';
                    echo date('d/m/Y',$pro['vreme_unosa']);
                echo '</td>';
                    echo '<td>';
                    echo '<a href="/admin/obrisiprojekat/id/'.$pro['id_projekta'].'" onclick="return confirm('."'Da li ste sigurni?'".');">Delete</a>';
                echo '</td>';
                echo '<td>';
                    echo '<a class="edit" href="javascript:void(0);">Edit</a> <button class="save btn btn-primary" style="display:none;" id="save_'.$pro['id_projekta'].'">Save</button>';
                echo '</td>';    

            echo '</tr>';
          }
    ?>
</table>
                    
                    
              </div>
               
           </div>
    </div>
</div>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
    $('.edit').click(function(){
        $(this).hide();
        $(this).parent().find('.save').show();
        
        var naziv =  $(this).parent().parent().find('.naziv_projekta');
        var opis =  $(this).parent().parent().find('.opis_projekta');
        var link =  $(this).parent().parent().find('.link_projekta');
        
        naziv.html('<textarea name="naziv" class="naziv_projekta" style="width:100%;height:100px;">'+naziv.html()+'</textarea>');
        opis.html('<textarea name="opis" class="opis_projekta" style="width:100%;height:100px;">'+opis.html()+'</textarea>');
        link.html('<textarea name="link" class="link_projekta" style="width:100%;height:100px;">'+link.html()+'</textarea>');
    });
    
    $('.save').click(function(){
        var save = $(this);
        var naziv =  $(this).parent().parent().find('.naziv_projekta');
        var opis =  $(this).parent().parent().find('.opis_projekta');
        var link =  $(this).parent().parent().find('.link_projekta');
        
        var id = save.attr('id').split('_');
        
        $.post("/admin/izmeniprojekat", { id: id[1], naziv: naziv.find("textarea").val(), opis: opis.find("textarea").val(), link: link.find("textarea").val() }, function(data){
            if(data){
                alert("Proizvod je uspesno izmenjen.");
                naziv.html(naziv.find("textarea").val());
                opis.html(opis.find("textarea").val());
                link.html(link.find("textarea").val());
                
                save.hide();
                save.parent().find(".edit").show();
            }else{
                alert("Nije uneto!");
            }
            
        });
    });
</script>